In [12]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)


In [13]:
#HOW LIKELY IS IT TO ROLL DOUBLES

In [14]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)


In [23]:
rolls[]

4

In [27]:
is_do = 0
x = 0
for i in rolls:
    if rolls[x,0] == rolls[x,1]:
        is_do += 1
        x += 1
    else:
        x += 1
is_do 

1709

In [34]:
print('Percent likelyhood of doubles:')
(is_do / 10_000 ) * 100

Percent likelyhood of doubles:


17.09

In [37]:
#COIN FLIPS
c_trials = nrows = 100_000
c_flips = ncols = 8

flips = np.random.choice([0, 1], c_trials * c_flips).reshape(nrows, ncols)
flips

array([[1, 1, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0]])

In [60]:
#chance for 3/8 heads
three_exact = flips.sum(axis=1)
test = (three_exact == 3)

In [66]:
(np.count_nonzero(test)) / 1000 #OUR EXPECTED PERCENTAGE OF EXACTLY 3 HEADS

21.952

In [67]:
#CHANCE FOR MORE THAN THREE HEADS

In [68]:
three_plus = flips.sum(axis=1)
test = (three_plus >= 3)

In [71]:
test

array([ True,  True,  True, ...,  True,  True,  True])

In [74]:
test.sum()/1000 #EXPECTED PERCENT CHANCE OF GETTING 4 OR MORE FLIPS TO GO YOUR WAY

85.742

In [75]:
#ONE IN 4 CHANCE OF SELECTING DS OVER WEB DEV

In [77]:
p_trials = nrows = 100_000
p_picks = ncols = 2

picks = np.random.choice(['DS', 'WD', 'WD', 'WD'], p_trials * p_picks).reshape(nrows, ncols)
picks

array([['DS', 'WD'],
       ['DS', 'WD'],
       ['WD', 'WD'],
       ...,
       ['WD', 'DS'],
       ['WD', 'WD'],
       ['DS', 'WD']], dtype='<U2')

In [99]:
is_bo = 0
xx = 0
for i in picks:
    if ((picks[xx, 0] == 'DS') and (picks[xx, 1] == 'DS')):
        is_bo += 1
        xx += 1
    else:
        xx += 1
is_bo / 1000

6.256

In [100]:
#EXPECTED CHANC OF 2 DS BILLBOARDS

In [ ]:
np.random.normal

In [101]:
#EXPECTED COBSUMPTION OF POPTARTS, 3+-1.5, 17 STOCKED, ANY AVAIL ON FRIADY

In [107]:
poptarts = np.random.normal(3, 1.5, size=(17,100000))

In [108]:
poptarts

array([[ 2.82399763,  5.83822888,  3.88640695, ...,  3.49583485,
         0.95514468,  2.43265697],
       [ 3.32052207,  2.71715607,  3.83643125, ...,  2.34765318,
         1.22316589,  0.04991995],
       [ 2.64734372,  4.07799489,  3.00266057, ...,  5.53262797,
         3.62080226,  4.63286657],
       ...,
       [ 2.65700889,  3.04064384,  2.13907482, ...,  2.86504871,
         2.34446153,  4.36565789],
       [ 3.21222104,  4.80119836,  3.08546296, ...,  2.08040507,
         0.78861789,  5.81074729],
       [ 2.62487337,  1.13048585,  0.74494299, ...,  2.18498331,
        -0.05147444,  5.26978013]])